# BRAIN-IoT service robotic .travis-ci.yml
# https://docs.gitlab.com/ce/ci/yaml/

# docker image with maven 3 and java 11
#image: maven:3-jdk-11

################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11


env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "'-s .m2/settings.xml -B'"
  MAVEN_DEPLOY_OPTS: "'-DaltReleaseDeploymentRepository=brain-iot-releases::default::https://nexus.repository-pert.ismb.it/repository/maven-releases -DaltSnapshotDeploymentRepository=brain-iot-snapshots::default::https://nexus.repository-pert.ismb.it/repository/maven-snapshots'"
#  CI_DEBUG_TRACE: "true"
  global:
  - secure:
    BKe36cP+z04VFmlrRUGhluTunDPJC+Aps8ksta5K0LGgnZeI+Geuq0Ccwds/qt5uB9ulKCg9cWYOwE24St96PSic+K4CgJ+NecxHWNjqDn1uIrj05e869k3MMg30WGMivwx9pMnH5f2qec8ZCnZxe4XbHEzLopdGMjxWTHHiy5mnHAP6aFY8M32dvd1VbFmLzBOjOMZi78NLaHd5GJHJKL0M2sVyILqsr3a4rLoNe8mvJ8hljbema/oPCy1sRZ7IKtTRWoeOPXXuWmrntRwPDydLS83AmftgAbtp+aSNBJ9vCeCi0jbXnDy1ThjItzq80ov6Dex3jcZ19ROvQr3I63FzpRyftgAE7wSiNOXBavB7yIu8n37HHaBCieFicRiFMTpEMK8XwuJ0hSagzfDb2p9S3lB9CDkmDb6W+nbmSFPAtxWan5exes7JtfEsVFSWt0PylXv3W1mNrDyO/gy3hCl8JoEcABNWhbh56H9ew7Q1g7Rhs3Sj+0c3Dw49GA+HBPzrlXVYNSfzF1AFdopvDORd0NOUHhd5gFXS1O/Trodof+nic4L8fLJ4Xbr2Hwk7/Z4m90nJBBOPTcq6fceJQDwUQzLGzhIAMTEwqIitmbEyvxpaFog7mcmEUYXnQNCWZ2TyZgQ1bphBfrGSu3nTEy4SPPWC6240j96QQd/TZnE=
  - secure: 
    sasfBJxOIrppY1Y1k6MDrmJNGVNdiQJA37CyyqMoh2rk6Fr0li8Ras1Y0DENx6TTe3WrmaffzTpcfKy5DztmVeeuT114Ks/EO1FMmeTMyE+osUFYZ/O1aQzTKZXWQ2/ZmFKZDYAyvRkKHmJR2KXIGr1PeYnA70kIxT5+h03um+DQqGb8pAtrH5N6UZBPUPg8sEl68G/dgYwxZJ2hEuPcnIH6nuMbtN/mBPeB/NIrlEDwn1vQWH0nVPG/AsAPqTC7PRJcVnsYM+e8Qw0Td2Z2u4xiLw5vdt45+TkVXT6qY4siM02fr21CFjmJfiUXRNqUhaHdWNcvwf/eCWA15iqCBmPTMqwRAiXC0LGN2j5I3HZ88QsJlcVn6aR73Lj4Gigl9wZuoFl0ODfo5MihBhB74k0+2YRQyaHJY9P2UqNbV0DOQBZXeILubmjLCeipFC0NZ6r2WyE/hgxD5dEV6IebEpyoVPozH173sIYtQKTQzkkL7lU2HA4G1IWbawHhuazXvoxEm+K+JxPp5AyOrYvUF/FKwBFcDliEu0uKHdnSeyPckbsI/uz7jutuQPs0FR+1Q5/OZnO2D+dBALY3z5pXsPBG95iR0Ecgqzua1RFpqAeZcsv55UaqbLXlK+dBBkfK5utpEbbUPqk0FUoMqUraojeuOzkA6F1T+VJZsl9fHz4=



  
# Cache downloaded dependencies and plugins between builds.
cache:
  directories:
    - $HOME/.m2/repository

before_install:
    - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
    - unzip -qq apache-maven-3.6.3-bin.zip
    - export M2_HOME=$PWD/apache-maven-3.6.3
    - export PATH=$M2_HOME/bin:$PATH

install:
    - mvn $MAVEN_CLI_OPTS package bnd-resolver:resolve

script:
    - mvn $MAVEN_CLI_OPTS bnd-export:export


after_success:
     - mvn $MAVEN_CLI_OPTS $MAVEN_DEPLOY_OPTS clean package org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy


#end